
server:
  port: 80

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://mocker.tech:3306/my_cloud_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Mockerli@1213


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: mocker.tech.springcloud.entities    # 所有Entity别名类所在包
 
 
